// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelDataService.Models;

#nullable disable

namespace TravelDataService.Migrations
{
    [DbContext(typeof(TravelDbContext))]
    [Migration("20260520155429_InicijalnaBaza")]
    partial class InicijalnaBaza
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelDataService.Models.Aktivnost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DestinacijaId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremePocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeZavrsetka")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DestinacijaId");

                    b.ToTable("Aktivnosti");
                });

            modelBuilder.Entity("TravelDataService.Models.Destinacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDolaska")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOdlaska")
                        .HasColumnType("datetime2");

                    b.Property<string>("Napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivMesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanPutovanjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanPutovanjaId");

                    b.ToTable("Destinacije");
                });

            modelBuilder.Entity("TravelDataService.Models.PlanPutovanja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPocetka")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumZavrsetka")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PlaniraniBudzet")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PlanoviPutovanja");
                });

            modelBuilder.Entity("TravelDataService.Models.Trosak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<double>("Iznos")
                        .HasColumnType("float");

                    b.Property<string>("Kategorija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlanPutovanjaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanPutovanjaId");

                    b.ToTable("Troskovi");
                });

            modelBuilder.Entity("TravelDataService.Models.Aktivnost", b =>
                {
                    b.HasOne("TravelDataService.Models.Destinacija", "Destinacija")
                        .WithMany("Aktivnosti")
                        .HasForeignKey("DestinacijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinacija");
                });

            modelBuilder.Entity("TravelDataService.Models.Destinacija", b =>
                {
                    b.HasOne("TravelDataService.Models.PlanPutovanja", "PlanPutovanja")
                        .WithMany("Destinacije")
                        .HasForeignKey("PlanPutovanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPutovanja");
                });

            modelBuilder.Entity("TravelDataService.Models.Trosak", b =>
                {
                    b.HasOne("TravelDataService.Models.PlanPutovanja", "PlanPutovanja")
                        .WithMany("Troskovi")
                        .HasForeignKey("PlanPutovanjaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanPutovanja");
                });

            modelBuilder.Entity("TravelDataService.Models.Destinacija", b =>
                {
                    b.Navigation("Aktivnosti");
                });

            modelBuilder.Entity("TravelDataService.Models.PlanPutovanja", b =>
                {
                    b.Navigation("Destinacije");

                    b.Navigation("Troskovi");
                });
#pragma warning restore 612, 618
        }
    }
}
